
version: "3.5"

services:
  api01: &api 
    image: gmessiasc/activej-crebito-native
    build: 
      context: .
        #dockerfile: Dockerfile.native
    hostname: api01
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=8080
    ports: 
       - "8081:8080"
        #network_mode: host
    volumes: 
       - pg-volume:/var/run/postgresql
    depends_on:
      db:
         condition: service_healthy
    deploy:
      resources:
       limits:
         cpus: "0.25"
         memory: "150MB"
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "-o", "/dev/null", "http://localhost:8080/health-check"]
      start_period: 2s
      interval: 2s
      timeout: 5s
      retries: 15

  api02:
    <<: *api 
    hostname: api02
      # network_mode: host
    environment:
      - HOSTNAME=0.0.0.0
      - PORT=8080
    ports:
      - "8082:8080"
    depends_on:
      db:
         condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "-s", "-o", "/dev/null", "http://localhost:8080/health-check"]
      start_period: 2s
      interval: 2s
      timeout: 5s
      retries: 15


  db:
    image: postgres:latest
    hostname: db
    ports:
      - "5432:5432"
    #network_mode: host
    environment:
      - POSTGRES_PASSWORD=rinha
      - POSTGRES_USER=rinha
      - POSTGRES_DB=crebito
    volumes:
      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg-volume:/var/run/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10m
      timeout: 5s
      start_period: 15s
      start_interval: 2s
      retries: 3
    command: [ "postgres", "-c", "config_file=/docker-entrypoint-initdb.d/postgresql.conf" ]
    deploy:
       resources:
         limits:
           cpus: "0.8"
           memory: "230MB"

  nginx:
    image: nginx:latest
    #network_mode: host
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api01:
        condition: service_healthy
      api02:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

volumes:
  pg-volume: 

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1
